export const groups = [
  [
    "입력",
    "Forms",
    [
      [
        "button",
        "Button",
        "명확한 행동을 위한 단 하나의 시작점.",
        "variant · size · loading · disabled",
        "Enter / Space로 실행합니다. 기본 type은 button입니다.",
      ],
      [
        "input",
        "Input",
        "단일 행의 텍스트를 입력합니다.",
        "value · onChange · type · disabled",
        "항상 연결된 label을 제공하세요. placeholder는 label을 대신하지 않습니다.",
      ],
      [
        "textarea",
        "Textarea",
        "긴 의견과 설명을 자연스럽게 입력합니다.",
        "value · onChange · maxLength · rows",
        "필요한 입력 길이를 안내하고 오류 원인을 텍스트로 제공합니다.",
      ],
      [
        "native-select",
        "Native Select",
        "간결한 목록에서 하나를 고릅니다.",
        "value · onChange · children",
        "브라우저 기본 키보드 탐색을 유지합니다.",
      ],
      [
        "field",
        "Field",
        "레이블, 안내, 오류를 하나의 흐름으로 연결합니다.",
        "label · required · description · error",
        "label 연결, aria-describedby, aria-invalid를 자동으로 연결합니다.",
      ],
      [
        "checkbox",
        "Checkbox",
        "독립적인 옵션을 선택하거나 해제합니다.",
        "checked · onCheckedChange · name",
        "Space로 선택합니다. indeterminate 상태를 지원합니다.",
      ],
      [
        "radio-group",
        "Radio Group",
        "여러 선택지 중 하나만 선택합니다.",
        "options · value · onValueChange",
        "방향키로 항목을 이동하고 선택합니다.",
      ],
      [
        "switch",
        "Switch",
        "즉시 적용되는 설정을 켜고 끕니다.",
        "checked · onCheckedChange · name",
        "Space로 전환합니다. 상태와 무관하게 label은 유지하세요.",
      ],
      [
        "slider",
        "Slider",
        "연속적인 범위 안에서 값을 조절합니다.",
        "value · min · max · step",
        "방향키로 step 이동, Home / End로 양 끝 값을 선택합니다.",
      ],
      [
        "number-field",
        "Number Field",
        "최솟값과 최댓값이 있는 숫자를 입력합니다.",
        "Input: type=number · min · max · step",
        "네이티브 숫자 입력을 활용하는 조합 패턴입니다. 서버 검증도 필요합니다.",
      ],
      ["pin-otp-input", "Pin / OTP Input", "인증 코드를 입력합니다."],
      ["tags-input", "Tags Input", "여러 값을 태그로 입력합니다."],
      ["combobox", "Combobox", "검색과 선택을 하나의 컨트롤로 제공합니다."],
      ["listbox", "Listbox", "목록에서 항목을 선택합니다."],
      ["editable", "Editable", "현재 화면에서 내용을 바로 수정합니다."],
      ["color-picker", "Color Picker", "색상 값을 선택합니다."],
      ["rating", "Rating", "정해진 척도로 평가합니다."],
    ],
  ],
  [
    "날짜와 시간",
    "Date & time",
    [
      [
        "calendar",
        "Calendar",
        "월 단위 일정을 탐색하고 날짜를 선택합니다.",
        "mode · selected · onSelect · disabled · locale",
        "방향키로 날짜를 이동하고 Enter로 선택합니다. 한국어 locale과 선택 불가 날짜를 지원합니다.",
      ],
      [
        "date-field",
        "Date Field",
        "날짜를 입력하고 기본 선택기로 고릅니다.",
        "Input: type=date · min · max",
        "네이티브 날짜 입력입니다. 표시 형식은 브라우저와 언어에 따라 달라집니다.",
      ],
      [
        "date-picker",
        "Date Picker",
        "팝업 달력에서 날짜를 선택합니다.",
        "label · value · onValueChange · min · max · name",
        "달력의 키보드 이동과 Esc 닫기를 지원합니다. 날짜는 YYYY-MM-DD 형식으로 전달합니다.",
      ],
      ["date-range-field", "Date Range Field", "시작일과 종료일을 입력합니다."],
      [
        "date-range-picker",
        "Date Range Picker",
        "달력에서 기간을 선택합니다.",
        "Calendar: mode=range · selected · onSelect",
        "Popover와 Calendar를 조합한 패턴입니다. 양 끝 날짜가 있어야 완료할 수 있습니다.",
      ],
      [
        "range-calendar",
        "Range Calendar",
        "연속된 날짜 범위를 선택합니다.",
        "Calendar: mode=range · min · max · excludeDisabled",
        "시작과 끝을 선택합니다. 업무 규칙에 따라 선택할 수 없는 날짜와 최소 기간을 지정하세요.",
      ],
      [
        "time-field",
        "Time Field",
        "시간을 명확하게 입력합니다.",
        "Input: type=time · step",
        "브라우저 기본 시간 입력을 사용합니다. 시간대 변환은 서비스 책임입니다.",
      ],
      [
        "time-range-field",
        "Time Range Field",
        "시작 시간과 종료 시간을 입력합니다.",
      ],
      ["month-picker", "Month Picker", "연도와 월을 선택합니다."],
      ["year-picker", "Year Picker", "연도를 선택합니다."],
    ],
  ],
  [
    "탐색",
    "Navigation",
    [
      [
        "accordion",
        "Accordion",
        "관련 정보를 필요한 만큼 펼쳐 봅니다.",
        "type · items · value · onValueChange",
        "Enter / Space로 펼치고, 방향키로 제목 간 이동합니다.",
      ],
      [
        "breadcrumb",
        "Breadcrumb",
        "현재 위치와 상위 경로를 보여줍니다.",
        "items: label · href",
        "마지막 항목에 aria-current=page를 제공합니다.",
      ],
      [
        "collapsible",
        "Collapsible",
        "보조 설명을 접고 펼칩니다.",
        "open · onOpenChange",
        "트리거가 펼침 상태를 스크린리더에 전달합니다.",
      ],
      ["navigation-menu", "Navigation Menu", "상위 메뉴로 이동합니다."],
      ["menubar", "Menubar", "데스크톱 앱의 메뉴를 제공합니다."],
      [
        "pagination",
        "Pagination",
        "결과를 페이지 단위로 탐색합니다.",
        "page · count · onPageChange",
        "양 끝에서 이전·다음을 비활성화합니다.",
      ],
      [
        "stepper",
        "Stepper",
        "여러 단계의 현재 위치를 명확히 보여줍니다.",
        "steps · current",
        "현재 단계는 aria-current=step으로 전달합니다. 이동 버튼은 별도로 구성합니다.",
      ],
      [
        "tabs",
        "Tabs",
        "같은 맥락의 콘텐츠를 전환합니다.",
        "value · defaultValue · onValueChange",
        "방향키로 전환합니다. 각 탭과 패널이 자동 연결됩니다.",
      ],
      [
        "tree",
        "Tree",
        "조직과 폴더의 계층 구조를 탐색합니다.",
        "nodes · expanded · selected · onSelect",
        "↑↓ 탐색, → 펼침, ← 접기, Home / End 이동, Enter 선택. 선택과 펼침을 구분합니다.",
      ],
      ["toolbar", "Toolbar", "자주 쓰는 작업을 한곳에 모읍니다."],
      [
        "toggle",
        "Toggle",
        "하나의 옵션을 누른 상태로 유지합니다.",
        "pressed · onPressedChange",
        "aria-pressed로 상태를 전달합니다.",
      ],
      [
        "toggle-group",
        "Toggle Group",
        "서로 관련된 옵션을 묶어 전환합니다.",
        "type · value · onValueChange",
        "방향키로 항목 사이를 탐색합니다. 각 항목에 명확한 이름을 제공합니다.",
      ],
    ],
  ],
  [
    "피드백과 레이어",
    "Feedback & overlays",
    [
      [
        "dialog",
        "Dialog",
        "집중이 필요한 짧은 작업을 별도 레이어에서 진행합니다.",
        "open · onOpenChange · placement",
        "열릴 때 포커스를 이동하고 가둡니다. Esc로 닫으면 트리거로 돌아갑니다.",
      ],
      [
        "alert-dialog",
        "Alert Dialog",
        "되돌리기 어려운 행동을 실행하기 전 확인합니다.",
        "open · onOpenChange · action · cancel",
        "취소 버튼으로 초기 포커스를 이동합니다. 바깥 클릭으로 닫히지 않습니다.",
      ],
      [
        "popover",
        "Popover",
        "현재 맥락의 가벼운 보조 작업을 제공합니다.",
        "open · onOpenChange · side",
        "Esc로 닫고 트리거로 돌아갑니다. 제목 또는 aria-label을 제공하세요.",
      ],
      [
        "tooltip",
        "Tooltip",
        "짧은 보조 설명을 호버와 포커스로 제공합니다.",
        "content · children",
        "키보드 포커스에서도 표시됩니다. 필수 정보는 툴팁에만 넣지 않습니다.",
      ],
      ["hover-card", "Hover Card", "항목의 추가 정보를 미리 봅니다."],
      [
        "dropdown-menu",
        "Dropdown Menu",
        "관련 작업을 하나의 메뉴로 정리합니다.",
        "onSelect · disabled",
        "방향키로 탐색, Enter로 선택, Esc로 닫습니다.",
      ],
      [
        "context-menu",
        "Context Menu",
        "선택한 영역의 관련 작업을 표시합니다.",
        "onSelect · disabled",
        "우클릭과 Shift + F10으로 열고 방향키로 탐색합니다.",
      ],
      [
        "toast",
        "Toast",
        "작업 결과를 흐름을 방해하지 않고 알립니다.",
        "open · onOpenChange · duration",
        "알림 영역으로 전달합니다. 중요한 오류에는 지속적인 안내도 함께 제공합니다.",
      ],
      [
        "progress",
        "Progress",
        "시간이 걸리는 작업의 진행률을 보여줍니다.",
        "value · max · label",
        "label과 현재 값이 보조 기술에 전달됩니다.",
      ],
      [
        "scroll-area",
        "Scroll Area",
        "제한된 공간에서 콘텐츠를 탐색합니다.",
        "height · children",
        "키보드로 스크롤할 수 있도록 뷰포트에 포커스를 허용합니다.",
      ],
      [
        "drawer",
        "Drawer",
        "현재 화면 옆에서 맥락을 유지하며 작업합니다.",
        "DialogContent: placement=right",
        "Dialog와 동일한 포커스 관리·Esc 동작을 사용합니다.",
      ],
      [
        "bottom-sheet",
        "Bottom Sheet",
        "아래에서 나타나는 보조 작업 영역입니다.",
        "DialogContent: placement=bottom",
        "Dialog 기반입니다. 드래그 제스처는 제공하지 않습니다.",
      ],
      [
        "alert",
        "Alert",
        "지속적으로 확인해야 하는 정보와 오류를 전달합니다.",
        "tone · children",
        "긴급 오류는 alert, 일반 안내는 status로 전달합니다.",
      ],
    ],
  ],
  [
    "데이터와 표현",
    "Data display",
    [
      [
        "badge",
        "Badge",
        "상태를 짧은 텍스트로 표시합니다.",
        "tone · children",
        "색상만으로 상태를 구분하지 않고 텍스트를 함께 제공합니다.",
      ],
      [
        "card",
        "Card",
        "관련 정보를 하나의 독립적인 단위로 묶습니다.",
        "children · HTML attributes",
        "의미 있는 제목을 포함하세요. 카드 전체에 중첩된 클릭 영역을 만들지 않습니다.",
      ],
      [
        "avatar",
        "Avatar",
        "사람이나 조직을 식별하는 이미지를 표시합니다.",
        "src · alt · fallback",
        "이미지 실패 시 대체 텍스트를 표시합니다.",
      ],
      [
        "table",
        "Table",
        "행과 열로 구조화된 정보를 비교합니다.",
        "caption · headers · rows",
        "caption과 열 제목을 제공합니다. 대용량 가상 스크롤은 별도 범위입니다.",
      ],
      [
        "list",
        "List",
        "동등한 정보 항목을 순서대로 보여줍니다.",
        "children: li",
        "실제 목록 태그를 사용합니다.",
      ],
      [
        "separator",
        "Separator",
        "콘텐츠 사이의 의미 있는 경계를 표현합니다.",
        "—",
        "구분선의 의미를 보조 기술에 전달합니다.",
      ],
      [
        "aspect-ratio",
        "Aspect Ratio",
        "미디어의 가로세로 비율을 일정하게 유지합니다.",
        "ratio · children",
        "미디어 자체에 대체 텍스트를 제공합니다.",
      ],
      ["splitter", "Splitter", "콘텐츠 패널의 크기를 조절합니다."],
      [
        "skeleton",
        "Skeleton",
        "로딩 중인 콘텐츠의 윤곽을 보여줍니다.",
        "width · height",
        "장식은 숨기고 외부 status 영역에서 로딩을 안내합니다. 모션 감소 설정을 존중합니다.",
      ],
      [
        "empty-state",
        "Empty State",
        "내용이 없는 이유와 다음 행동을 안내합니다.",
        "title · description · children",
        "상황을 설명하는 제목과 가능한 다음 행동을 제공합니다.",
      ],
      [
        "timeline",
        "Timeline",
        "시간의 순서에 따라 이력을 보여줍니다.",
        "items: title · description",
        "순서 있는 목록으로 읽힙니다.",
      ],
      ["carousel", "Carousel", "연속된 콘텐츠를 순차적으로 탐색합니다."],
    ],
  ],
] as const;
export type Entry = {
  id: string;
  name: string;
  description: string;
  api: string;
  accessibility: string;
  group: string;
};
export const entries: Entry[] = groups.flatMap(([group, , items]) =>
  items.map((item) => ({
    id: item[0],
    name: item[1],
    description: item[2],
    api: (item as readonly string[])[3] || "",
    accessibility: (item as readonly string[])[4] || "",
    group,
  })),
);
