import type { ChoiceOption } from "./Collections.js";

export type OptionsLoader = (
  query: string,
  context: { signal: AbortSignal },
) => Promise<ChoiceOption[]>;
/** GET JSON array of {value,label,disabled?,description?}; custom APIs can supply their own loader. */
export function createOptionsLoader(
  endpoint: string,
  init?: Omit<RequestInit, "signal" | "method">,
): OptionsLoader {
  return async (query, { signal }) => {
    const url = new URL(endpoint, globalThis.location?.href);
    url.searchParams.set("q", query);
    const response = await fetch(url, { ...init, method: "GET", signal });
    if (!response.ok) throw new Error("검색 요청에 실패했습니다.");
    const items: unknown = await response.json();
    if (
      !Array.isArray(items) ||
      !items.every(
        (item) =>
          typeof item?.value === "string" &&
          item.value.length > 0 &&
          typeof item.label === "string",
      )
    )
      throw new Error("검색 응답 형식이 올바르지 않습니다.");
    return items;
  };
}
export type DataRow = Record<
  string,
  string | number | boolean | null | undefined
>;
export interface TableColumn {
  key: string;
  label: string;
  sortable?: boolean;
  width?: number;
}
export interface TableQuery {
  page: number;
  pageSize: number;
  search: string;
  sort: { key: string; direction: "asc" | "desc" } | null;
}
export interface TableResult<T = DataRow> {
  rows: T[];
  total: number;
}
export type RowsLoader<T = DataRow> = (
  query: TableQuery,
  context: { signal: AbortSignal },
) => Promise<TableResult<T>>;
export function queryRows<T extends DataRow>(
  rows: T[],
  columns: TableColumn[],
  query: TableQuery,
): TableResult<T> {
  const term = query.search.trim().toLocaleLowerCase();
  let filtered = rows.filter(
    (row) =>
      !term ||
      columns.some((column) =>
        String(row[column.key] ?? "")
          .toLocaleLowerCase()
          .includes(term),
      ),
  );
  if (query.sort) {
    const { key, direction } = query.sort;
    filtered = [...filtered].sort((a, b) => {
      const x = a[key],
        y = b[key];
      const order =
        typeof x === "number" && typeof y === "number"
          ? x - y
          : String(x ?? "").localeCompare(String(y ?? ""), "ko", {
              numeric: true,
            });
      return direction === "asc" ? order : -order;
    });
  }
  return {
    total: filtered.length,
    rows: filtered.slice(
      (query.page - 1) * query.pageSize,
      query.page * query.pageSize,
    ),
  };
}
export interface UploadContext {
  signal: AbortSignal;
  onProgress: (percent: number) => void;
}
export type UploadHandler = (
  file: File,
  context: UploadContext,
) => Promise<unknown>;
export interface UploadItem {
  id: string;
  file: File;
  status: "queued" | "uploading" | "success" | "error" | "canceled";
  progress: number;
  error?: string;
  result?: unknown;
}
export interface UploadRules {
  accept?: string;
  maxFiles?: number;
  maxSize?: number;
}
/** Client-side hints only: the server must validate type, content, size and permission again. */
export function validateFile(
  file: File,
  rules: UploadRules,
): string | undefined {
  if (rules.maxSize && file.size > rules.maxSize)
    return "허용된 파일 크기를 초과했습니다.";
  const allowed =
    rules.accept
      ?.split(",")
      .map((value) => value.trim().toLowerCase())
      .filter(Boolean) ?? [];
  if (
    allowed.length &&
    !allowed.some((type) =>
      type.startsWith(".")
        ? file.name.toLowerCase().endsWith(type)
        : type.endsWith("/*")
          ? file.type.toLowerCase().startsWith(type.slice(0, -1))
          : file.type.toLowerCase() === type,
    )
  )
    return "지원하지 않는 파일 형식입니다.";
}
/** Multipart POST. Content-Type is generated by the browser, never set it manually. */
export function createXHRUpload(
  endpoint: string,
  options: {
    fieldName?: string;
    headers?: Record<string, string>;
    withCredentials?: boolean;
    timeout?: number;
  } = {},
): UploadHandler {
  return (file, { signal, onProgress }) =>
    new Promise((resolve, reject) => {
      if (signal.aborted) {
        reject(new DOMException("Canceled", "AbortError"));
        return;
      }
      const xhr = new XMLHttpRequest();
      const abort = () => xhr.abort();
      const cleanup = () => signal.removeEventListener("abort", abort);
      xhr.open("POST", endpoint);
      xhr.withCredentials = options.withCredentials ?? false;
      xhr.timeout = options.timeout ?? 120000;
      for (const [key, value] of Object.entries(options.headers ?? {}))
        if (key.toLowerCase() !== "content-type")
          xhr.setRequestHeader(key, value);
      xhr.upload.onprogress = (event) => {
        if (event.lengthComputable)
          onProgress(
            Math.min(99, Math.round((event.loaded / event.total) * 100)),
          );
      };
      xhr.onload = () => {
        cleanup();
        if (xhr.status >= 200 && xhr.status < 300) {
          onProgress(100);
          resolve(xhr.responseText);
        } else reject(new Error("업로드에 실패했습니다. 다시 시도해 주세요."));
      };
      xhr.onerror = () => {
        cleanup();
        reject(new Error("네트워크 연결을 확인해 주세요."));
      };
      xhr.ontimeout = () => {
        cleanup();
        reject(new Error("업로드 시간이 초과되었습니다."));
      };
      xhr.onabort = () => {
        cleanup();
        reject(new DOMException("Canceled", "AbortError"));
      };
      signal.addEventListener("abort", abort, { once: true });
      const data = new FormData();
      data.append(options.fieldName ?? "file", file);
      xhr.send(data);
    });
}
/** Per-instance queue. Abort plus identity guards prevent late progress/results after cancel/retry. */
export class UploadQueue {
  items: UploadItem[] = [];
  private controllers = new Map<string, AbortController>();
  private sequence = 0;
  private disposed = false;
  constructor(
    private changed: (items: UploadItem[]) => void,
    private complete?: (item: UploadItem) => void,
  ) {}
  private publish() {
    if (!this.disposed) this.changed([...this.items]);
  }
  add(files: File[], rules: UploadRules): string[] {
    const errors: string[] = [];
    for (const file of files) {
      if (this.items.length >= (rules.maxFiles ?? 5)) {
        errors.push("선택 가능한 파일 수를 초과했습니다.");
        break;
      }
      const issue = validateFile(file, rules);
      if (issue) {
        errors.push(file.name + ": " + issue);
        continue;
      }
      if (
        this.items.some(
          (item) =>
            item.file.name === file.name &&
            item.file.size === file.size &&
            item.file.lastModified === file.lastModified,
        )
      ) {
        errors.push(file.name + ": 이미 추가한 파일입니다.");
        continue;
      }
      this.items = [
        ...this.items,
        {
          id: "upload-" + ++this.sequence,
          file,
          status: "queued",
          progress: 0,
        },
      ];
    }
    this.publish();
    return errors;
  }
  async start(id: string, upload: UploadHandler) {
    const item = this.items.find((item) => item.id === id);
    if (
      !item ||
      this.disposed ||
      item.status === "uploading" ||
      item.status === "success"
    )
      return;
    const controller = new AbortController();
    this.controllers.set(id, controller);
    const current = () =>
      !this.disposed &&
      !controller.signal.aborted &&
      this.controllers.get(id) === controller &&
      this.items.includes(item);
    item.status = "uploading";
    item.progress = 0;
    item.error = undefined;
    this.publish();
    try {
      const result = await upload(item.file, {
        signal: controller.signal,
        onProgress: (percent) => {
          if (current() && Number.isFinite(percent)) {
            item.progress = Math.max(
              item.progress,
              Math.min(99, Math.max(0, percent)),
            );
            this.publish();
          }
        },
      });
      if (current()) {
        item.status = "success";
        item.progress = 100;
        item.result = result;
        this.publish();
        this.complete?.({ ...item });
      }
    } catch {
      if (current()) {
        item.status = "error";
        item.error = "업로드에 실패했습니다. 다시 시도해 주세요.";
        this.publish();
      }
    } finally {
      if (this.controllers.get(id) === controller) this.controllers.delete(id);
    }
  }
  cancel(id: string) {
    const item = this.items.find((item) => item.id === id);
    this.controllers.get(id)?.abort();
    this.controllers.delete(id);
    if (item && item.status !== "success") {
      item.status = "canceled";
      item.progress = 0;
      this.publish();
    }
  }
  remove(id: string) {
    this.cancel(id);
    this.items = this.items.filter((item) => item.id !== id);
    this.publish();
  }
  clear() {
    for (const item of this.items) this.controllers.get(item.id)?.abort();
    this.controllers.clear();
    this.items = [];
    this.publish();
  }
  dispose() {
    this.disposed = true;
    this.clear();
  }
}
